package io.github.cshunsinger.asmsauce.code;

import io.github.cshunsinger.asmsauce.ThisClass;
import io.github.cshunsinger.asmsauce.code.branch.IfBranch;
import io.github.cshunsinger.asmsauce.code.branch.WhileLoop;
import io.github.cshunsinger.asmsauce.code.branch.condition.Condition;
import io.github.cshunsinger.asmsauce.code.cast.ExplicitConversionInsn;
import io.github.cshunsinger.asmsauce.code.field.GetStaticFieldInsn;
import io.github.cshunsinger.asmsauce.code.method.InstantiateObjectInsn;
import io.github.cshunsinger.asmsauce.code.method.InvokeBaseConstructorInsn;
import io.github.cshunsinger.asmsauce.code.method.InvokeStaticMethodInsn;
import io.github.cshunsinger.asmsauce.code.method.ReturnInsn;
import io.github.cshunsinger.asmsauce.code.stack.StackLocalVariableInsn;
import io.github.cshunsinger.asmsauce.code.stack.StackObjectLiteralInsn;
import io.github.cshunsinger.asmsauce.code.stack.StackPrimitiveLiteralInsn;
import io.github.cshunsinger.asmsauce.code.stack.StoreLocalVariableInsn;
import io.github.cshunsinger.asmsauce.code.field.AssignStaticFieldInsn;
import io.github.cshunsinger.asmsauce.definitions.*;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;

import java.lang.reflect.Constructor;

import static io.github.cshunsinger.asmsauce.DefinitionBuilders.*;
import static io.github.cshunsinger.asmsauce.modifiers.AccessModifiers.privateStatic;
import static io.github.cshunsinger.asmsauce.modifiers.AccessModifiers.publicStatic;

/**
 * This class contains all of the static methods which can be used to create all of the code building instructions.
 * Like with DefinitionBuilders {@link io.github.cshunsinger.asmsauce.DefinitionBuilders} it is recommended to use a static import to access the
 * methods in this class.
 *
 * @see io.github.cshunsinger.asmsauce.DefinitionBuilders
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class CodeBuilders {
    /**
     * Shortcut method to stack the local variable at index-0 onto the jvm stack. When building an instance method,
     * the stacked value will be a reference to 'this'.
     * @return A code builder which stacks a reference to 'this' when building an instance method.
     * @see #getVar(int) To stack a local variable at a given index.
     * @see #getVar(String) To stack a named local variable or parameter by name.
     */
    public static StackLocalVariableInsn this_() {
        return getVar(0);
    }

    /**
     * Stack a local variable or parameter at a given index.
     * @param localIndex The index of the local variable to stack.
     * @return A code builder which will stack a local variable at the given localIndex onto the jvm stack.
     * @see #this_()
     * @see #getVar(String) To stack a named local variable or parameter by name.
     */
    public static StackLocalVariableInsn getVar(int localIndex) {
        return new StackLocalVariableInsn(localIndex);
    }

    /**
     * Stack a named local variable or parameter. This method will not work for stacking unnamed local variables or parameters.
     * @param localName The name of the local variable or parameter to stack.
     * @return A code builder which will stack a named local variable or parameter with the given name onto the jvm stack.
     * @see #this_()
     * @see #getVar(int) To stack a local variable at a given index.
     */
    public static StackLocalVariableInsn getVar(String localName) {
        return new StackLocalVariableInsn(localName);
    }

    /**
     * Set a local variable at a given index.
     * @param localIndex The index of the local variable to store the value to.
     * @param valueBuilder The code builder which stacks a value to be stored to the local variable.
     * @return A code builder whose generated bytecode will store a value to a local variable.
     * @see #setVar(CodeInsnBuilderLike)
     * @see #setVar(String, CodeInsnBuilderLike)
     */
    public static StoreLocalVariableInsn setVar(Integer localIndex, CodeInsnBuilderLike valueBuilder) {
        return new StoreLocalVariableInsn(localIndex, valueBuilder);
    }

    /**
     * Creates a new local variable with a new index, and sets it to a value.
     * @param valueBuilder The code builder which stacks a value to be stored to the new local variable.
     * @return A code builder whose generated bytecode will store a value to a new local variable.
     * @see #setVar(Integer, CodeInsnBuilderLike)
     * @see #setVar(String, CodeInsnBuilderLike)
     */
    public static StoreLocalVariableInsn setVar(CodeInsnBuilderLike valueBuilder) {
        return setVar((Integer)null, valueBuilder);
    }

    /**
     * Sets a value to a named local variable. If no named local variable exists then a new one will be created.
     * @param localName The name of the local variable to set.
     * @param valueBuilder The code builder which stacks a value to be stored to the named local variable.
     * @return A code builder whose generated bytecode will store a value to the named local variable, creating a new one if necessary.
     * @see #setVar(Integer, CodeInsnBuilderLike)
     * @see #setVar(CodeInsnBuilderLike)
     */
    public static StoreLocalVariableInsn setVar(String localName, CodeInsnBuilderLike valueBuilder) {
        return new StoreLocalVariableInsn(localName, valueBuilder);
    }

    /**
     * Calls a super constructor at the beginning of a constructor body. Equivalent to super(...);
     * @param constructor The constructor to invoke.
     * @param paramStackBuilders Code builders to stack the constructor parameters.
     * @return A code builder which generates bytecode to call a super constructor.
     * @see #superConstructor(TypeDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #superConstructor(Class, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #thisConstructor(ParametersDefinition, CodeInsnBuilderLike...)
     */
    public static InvokeBaseConstructorInsn superConstructor(Constructor<?> constructor, CodeInsnBuilderLike... paramStackBuilders) {
        return new InvokeBaseConstructorInsn(constructor, paramStackBuilders);
    }

    /**
     * Calls a super constructor at the beginning of a constructor body. Equivalent to super(...);
     * @param owner The owner of the super constructor.
     * @param parameters The parameters of the super constructor.
     * @param paramStackBuilders Code builders to stack the constructor parameters.
     * @return A code builder which generates bytecode to call a super constructor.
     * @see #superConstructor(Constructor, CodeInsnBuilderLike...)
     * @see #superConstructor(Class, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #thisConstructor(ParametersDefinition, CodeInsnBuilderLike...)
     */
    public static InvokeBaseConstructorInsn superConstructor(TypeDefinition owner, ParametersDefinition parameters, CodeInsnBuilderLike... paramStackBuilders) {
        return new InvokeBaseConstructorInsn(owner, parameters, noThrows(), paramStackBuilders);
    }

    /**
     * Calls a super constructor at the beginning of a constructor body. Equivalent to super(...);
     * @param ownerClass The owner of the super constructor.
     * @param parameters The parameters of the super constructor.
     * @param paramStackBuilders Code builders to stack the constructor parameters.
     * @return A code builder which generates bytecode to call a super constructor.
     * @see #superConstructor(TypeDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #superConstructor(Constructor, CodeInsnBuilderLike...)
     * @see #thisConstructor(ParametersDefinition, CodeInsnBuilderLike...)
     */
    public static InvokeBaseConstructorInsn superConstructor(Class<?> ownerClass, ParametersDefinition parameters, CodeInsnBuilderLike... paramStackBuilders) {
        return superConstructor(type(ownerClass), parameters, paramStackBuilders);
    }

    /**
     *
     * @param parameters The parameters of the other constructor in
     * @param paramStackBuilders Code builders to stack the constructor parameters.
     * @return A code builder which generates bytecode to call another constructor in the class being generated.
     * @see #superConstructor(Constructor, CodeInsnBuilderLike...)
     * @see #superConstructor(TypeDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #superConstructor(Class, ParametersDefinition, CodeInsnBuilderLike...)
     */
    public static InvokeBaseConstructorInsn thisConstructor(ParametersDefinition parameters, CodeInsnBuilderLike... paramStackBuilders) {
        return superConstructor(ThisClass.class, parameters, paramStackBuilders);
    }

    /**
     * Stack null.
     * @return A code builder whose bytecode places a null reference onto the jvm stack.
     */
    public static StackObjectLiteralInsn stackNull() {
        return literalObj(null);
    }

    /**
     * Stack a String or Class-literal.
     * @param obj The String or Class to stack.
     * @return A code builder whose bytecode places a literal String or Class onto the jvm stack.
     * @see #literal(byte)
     * @see #literal(short)
     * @see #literal(char)
     * @see #literal(int)
     * @see #literal(long)
     * @see #literal(float)
     * @see #literal(double)
     * @see #literal(boolean)
     * @see #true_()
     * @see #false_()
     */
    public static StackObjectLiteralInsn literalObj(Object obj) {
        return new StackObjectLiteralInsn(obj);
    }

    /**
     * Stack a literal byte.
     * @param b The byte to stack.
     * @return A code builder whose bytecode places a literal byte onto the jvm stack.
     * @see #literalObj(Object)
     * @see #literal(short)
     * @see #literal(char)
     * @see #literal(int)
     * @see #literal(long)
     * @see #literal(float)
     * @see #literal(double)
     * @see #literal(boolean)
     * @see #true_()
     * @see #false_()
     */
    public static StackPrimitiveLiteralInsn literal(byte b) {
        return new StackPrimitiveLiteralInsn(b);
    }

    /**
     * Stack a literal short.
     * @param s The short to stack.
     * @return A code builder whose bytecode places a literal short onto the jvm stack.
     * @see #literalObj(Object)
     * @see #literal(byte)
     * @see #literal(char)
     * @see #literal(int)
     * @see #literal(long)
     * @see #literal(float)
     * @see #literal(double)
     * @see #literal(boolean)
     * @see #true_()
     * @see #false_()
     */
    public static StackPrimitiveLiteralInsn literal(short s) {
        return new StackPrimitiveLiteralInsn(s);
    }

    /**
     * Stack a literal char.
     * @param c The char to stack.
     * @return A code builder whose bytecode places a literal char onto the jvm stack.
     * @see #literalObj(Object)
     * @see #literal(byte)
     * @see #literal(short)
     * @see #literal(int)
     * @see #literal(long)
     * @see #literal(float)
     * @see #literal(double)
     * @see #literal(boolean)
     * @see #true_()
     * @see #false_()
     */
    public static StackPrimitiveLiteralInsn literal(char c) {
        return new StackPrimitiveLiteralInsn(c);
    }

    /**
     * Stack a literal int.
     * @param i The int to stack.
     * @return A code builder whose bytecode places a literal int onto the jvm stack.
     * @see #literalObj(Object)
     * @see #literal(byte)
     * @see #literal(short)
     * @see #literal(char)
     * @see #literal(long)
     * @see #literal(float)
     * @see #literal(double)
     * @see #literal(boolean)
     * @see #true_()
     * @see #false_()
     */
    public static StackPrimitiveLiteralInsn literal(int i) {
        return new StackPrimitiveLiteralInsn(i);
    }

    /**
     * Stack a literal long.
     * @param l The long to stack.
     * @return A code builder whose bytecode places a literal long onto the jvm stack.
     * @see #literalObj(Object)
     * @see #literal(byte)
     * @see #literal(short)
     * @see #literal(char)
     * @see #literal(int)
     * @see #literal(float)
     * @see #literal(double)
     * @see #literal(boolean)
     * @see #true_()
     * @see #false_()
     *
     */
    public static StackPrimitiveLiteralInsn literal(long l) {
        return new StackPrimitiveLiteralInsn(l);
    }

    /**
     * Stack a literal float.
     * @param f The float to stack.
     * @return A code builder whose bytecode places a literal float onto the jvm stack.
     * @see #literalObj(Object)
     * @see #literal(byte)
     * @see #literal(short)
     * @see #literal(char)
     * @see #literal(int)
     * @see #literal(long)
     * @see #literal(double)
     * @see #literal(boolean)
     * @see #true_()
     * @see #false_()
     */
    public static StackPrimitiveLiteralInsn literal(float f) {
        return new StackPrimitiveLiteralInsn(f);
    }

    /**
     * Stack a literal double.
     * @param d The double to stack.
     * @return A code builder whose bytecode places a literal double onto the jvm stack.
     * @see #literalObj(Object)
     * @see #literal(byte)
     * @see #literal(short)
     * @see #literal(char)
     * @see #literal(int)
     * @see #literal(long)
     * @see #literal(float)
     * @see #literal(boolean)
     * @see #true_()
     * @see #false_()
     */
    public static StackPrimitiveLiteralInsn literal(double d) {
        return new StackPrimitiveLiteralInsn(d);
    }

    /**
     * Stack a literal boolean.
     * @param b The boolean to stack.
     * @return A code builder whose bytecode places a literal boolean onto the jvm stack.
     * @see #literalObj(Object)
     * @see #literal(byte)
     * @see #literal(short)
     * @see #literal(char)
     * @see #literal(int)
     * @see #literal(long)
     * @see #literal(float)
     * @see #literal(double)
     * @see #true_()
     * @see #false_()
     */
    public static StackPrimitiveLiteralInsn literal(boolean b) {
        return new StackPrimitiveLiteralInsn(b);
    }

    /**
     * Stack boolean-true.
     * @return A code builder whose bytecode places boolean-true onto the stack.
     * @see #literalObj(Object)
     * @see #literal(byte)
     * @see #literal(short)
     * @see #literal(char)
     * @see #literal(int)
     * @see #literal(long)
     * @see #literal(float)
     * @see #literal(double)
     * @see #literal(boolean)
     * @see #false_()
     */
    public static StackPrimitiveLiteralInsn true_() {
        return literal(true);
    }

    /**
     * Stack boolean-false.
     * @return A code builder whose bytecode places boolean-false onto the stack.
     * @see #literalObj(Object)
     * @see #literal(byte)
     * @see #literal(short)
     * @see #literal(char)
     * @see #literal(int)
     * @see #literal(long)
     * @see #literal(float)
     * @see #literal(double)
     * @see #literal(boolean)
     * @see #true_()
     * @see #false_()
     */
    public static StackPrimitiveLiteralInsn false_() {
        return literal(false);
    }

    /**
     * Return from a void method.
     * @return A code builder which produces the bytecode to return from a void method.
     * @see #returnValue(CodeInsnBuilderLike) For returning a value.
     */
    public static ReturnInsn returnVoid() {
        return returnValue(null);
    }

    /**
     * Return a value from a non-void method.
     * @param codeInsnBuilder The code builder which stacks the value to return.
     * @return A code builder which produces the bytecode to return a value from a non-void method.
     * @see #returnVoid() For returning nothing from a void method.
     */
    public static ReturnInsn returnValue(CodeInsnBuilderLike codeInsnBuilder) {
        return new ReturnInsn(codeInsnBuilder);
    }

    /**
     * Invoke a static method.
     * @param ownerType Owner of the method.
     * @param name Name of the method.
     * @param paramBuilders Code builders to stack values to pass as parameters.
     * @return A code builder which produces the bytecode to invoke a static method.
     * @see #invokeStatic(Class, String, CodeInsnBuilderLike...)
     * @see #invokeStatic(Class, NameDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(Class, NameDefinition, ParametersDefinition, TypeDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, ParametersDefinition, TypeDefinition, CodeInsnBuilderLike...)
     */
    public static InvokeStaticMethodInsn invokeStatic(TypeDefinition ownerType, NameDefinition name, CodeInsnBuilderLike... paramBuilders) {
        return new InvokeStaticMethodInsn(ownerType, name, paramBuilders);
    }

    /**
     * Invoke a static method.
     * @param ownerClass Owner of the method.
     * @param name Name of the method.
     * @param paramBuilders Code builders to stack values to pass as parameters.
     * @return A code builder which produces the bytecode to invoke a static method.
     * @see #invokeStatic(TypeDefinition, NameDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(Class, NameDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(Class, NameDefinition, ParametersDefinition, TypeDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, ParametersDefinition, TypeDefinition, CodeInsnBuilderLike...)
     */
    public static InvokeStaticMethodInsn invokeStatic(Class<?> ownerClass, String name, CodeInsnBuilderLike... paramBuilders) {
        return invokeStatic(type(ownerClass), name(name), paramBuilders);
    }

    /**
     * Invoke a static method.
     * @param type Owner of the method.
     * @param name Name of the method.
     * @param parameters Parameters of the method to call.
     * @param returnType Return type of the method being called.
     * @param paramBuilders Code builders to stack values to pass as parameters.
     * @return A code builder which produces the bytecode to invoke a static method.
     * @see #invokeStatic(Class, String, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(Class, NameDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, ParametersDefinition, TypeDefinition, CodeInsnBuilderLike...)
     */
    public static InvokeStaticMethodInsn invokeStatic(TypeDefinition type, NameDefinition name, ParametersDefinition parameters, TypeDefinition returnType, CodeInsnBuilderLike... paramBuilders) {
        return new InvokeStaticMethodInsn(type, name, parameters, returnType, noThrows(), paramBuilders);
    }

    /**
     * Invoke a static method.
     * @param typeClass Owner of the method.
     * @param name Name of the method.
     * @param parameters Parameters of the method to call.
     * @param returnType Return type of the method being called.
     * @param parameterBuilders Code builders to stack values to pass as parameters.
     * @return A code builder which produces the bytecode to invoke a static method.
     * @see #invokeStatic(Class, String, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(Class, NameDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, ParametersDefinition, TypeDefinition, CodeInsnBuilderLike...)
     */
    public static InvokeStaticMethodInsn invokeStatic(Class<?> typeClass, NameDefinition name, ParametersDefinition parameters, TypeDefinition returnType, CodeInsnBuilderLike... parameterBuilders) {
        return invokeStatic(type(typeClass), name, parameters, returnType, parameterBuilders);
    }

    /**
     * Invoke a static method.
     * @param type Owner of the method.
     * @param name Name of the method.
     * @param parameters Parameters of the method to call.
     * @param parameterBuilders Code builders to stack values to pass as parameters.
     * @return A code builder which produces the bytecode to invoke a static method.
     * @see #invokeStatic(Class, String, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(Class, NameDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(Class, NameDefinition, ParametersDefinition, TypeDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, ParametersDefinition, TypeDefinition, CodeInsnBuilderLike...)
     */
    public static InvokeStaticMethodInsn invokeStatic(TypeDefinition type, NameDefinition name, ParametersDefinition parameters, CodeInsnBuilderLike... parameterBuilders) {
        return new InvokeStaticMethodInsn(type, name, parameters, voidType(), noThrows(), parameterBuilders);
    }

    /**
     * Invoke a static method.
     * @param typeClass Owner of the method.
     * @param name Name of the method.
     * @param parameters Parameters of the method to call.
     * @param parameterBuilders Code builders to stack values to pass as parameters.
     * @return A code builder which produces the bytecode to invoke a static method.
     * @see #invokeStatic(Class, String, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(Class, NameDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #invokeStatic(TypeDefinition, NameDefinition, ParametersDefinition, TypeDefinition, CodeInsnBuilderLike...)
     */
    public static InvokeStaticMethodInsn invokeStatic(Class<?> typeClass, NameDefinition name, ParametersDefinition parameters, CodeInsnBuilderLike... parameterBuilders) {
        return invokeStatic(type(typeClass), name, parameters, parameterBuilders);
    }

    /**
     * Get a value from a static field.
     * @param owner Owner of the static field.
     * @param name Name of the static field.
     * @param fieldType Static field type.
     * @return A code builder which produces the bytecode to access a static field.
     * @see #getStatic(TypeDefinition, NameDefinition)
     * @see #getStatic(Class, String)
     */
    public static GetStaticFieldInsn getStatic(TypeDefinition owner, NameDefinition name, TypeDefinition fieldType) {
        return new GetStaticFieldInsn(new CompleteFieldDefinition(
            publicStatic(), //Access is irrelevant here, other than that this be static
            owner, name, fieldType
        ));
    }

    /**
     * Get a value from a static field.
     * @param owner Owner of the static field.
     * @param name Name of the static field.
     * @return A code builder which produces the bytecode to access a static field.
     * @see #getStatic(TypeDefinition, NameDefinition, TypeDefinition)
     * @see #getStatic(Class, String)
     */
    public static GetStaticFieldInsn getStatic(TypeDefinition owner, NameDefinition name) {
        return new GetStaticFieldInsn(new FieldDefinition(privateStatic(), owner, name, null));
    }

    /**
     * Get a value from a static field.
     * @param ownerClass Owner of the static field.
     * @param fieldName Name of the static field.
     * @return A code builder which produces the bytecode to access a static field.
     * @see #getStatic(TypeDefinition, NameDefinition, TypeDefinition)
     * @see #getStatic(TypeDefinition, NameDefinition)
     */
    public static GetStaticFieldInsn getStatic(Class<?> ownerClass, String fieldName) {
        return getStatic(type(ownerClass), name(fieldName));
    }

    /**
     * Assign a value to a static field.
     * @param owner Owner of the static field.
     * @param name Name of the static field.
     * @param fieldType Static field type.
     * @param valueBuilder Code builder which stacks a value to assign to the static field.
     * @return A code builder which produces the bytecode to assign a value to a static field.
     * @see #setStatic(Class, String, CodeInsnBuilderLike)
     * @see #setStatic(TypeDefinition, NameDefinition, CodeInsnBuilderLike)
     */
    public static AssignStaticFieldInsn setStatic(TypeDefinition owner, NameDefinition name, TypeDefinition fieldType, CodeInsnBuilderLike valueBuilder) {
        return new AssignStaticFieldInsn(new CompleteFieldDefinition(
            publicStatic(),
            owner, name, fieldType
        ), valueBuilder);
    }

    /**
     * Assign a value to a static field.
     * @param owner Owner of the static field.
     * @param name Name of the static field.
     * @param valueBuilder Code builder which stacks a value to assign to the static field.
     * @return A code builder which produces the bytecode to assign a value to a static field.
     * @see #setStatic(TypeDefinition, NameDefinition, TypeDefinition, CodeInsnBuilderLike)
     * @see #setStatic(Class, String, CodeInsnBuilderLike)
     */
    public static AssignStaticFieldInsn setStatic(TypeDefinition owner, NameDefinition name, CodeInsnBuilderLike valueBuilder) {
        return new AssignStaticFieldInsn(new FieldDefinition(
            publicStatic(),
            owner, name, null
        ), valueBuilder);
    }

    /**
     * Assign a value to a static field.
     * @param owner Owner of the static field.
     * @param name Name of the static field.
     * @param valueBuilder Code builder which stacks a value to assign to the static field.
     * @return A code builder which produces the bytecode to assign a value to a static field.
     * @see #setStatic(TypeDefinition, NameDefinition, TypeDefinition, CodeInsnBuilderLike)
     * @see #setStatic(TypeDefinition, NameDefinition, CodeInsnBuilderLike)
     */
    public static AssignStaticFieldInsn setStatic(Class<?> owner, String name, CodeInsnBuilderLike valueBuilder) {
        return setStatic(type(owner), name(name), valueBuilder);
    }

    /**
     * Explicitly cast a value.
     * @param toType The type to cast to.
     * @param valueBuilder Code builder which stacks a value to be cast.
     * @return A code builder which produces the bytecode to cast a value.
     * @see #cast(Class, CodeInsnBuilderLike)
     */
    public static ExplicitConversionInsn cast(TypeDefinition toType, CodeInsnBuilderLike valueBuilder) {
        return new ExplicitConversionInsn(toType, valueBuilder);
    }

    /**
     * Explicitly cast a value.
     * @param toType The type to cast to.
     * @param valueBuilder Code builder which stacks a value to be cast.
     * @return A code builder which produces the bytecode to cast a value.
     * @see #cast(TypeDefinition, CodeInsnBuilderLike)
     */
    public static ExplicitConversionInsn cast(Class<?> toType, CodeInsnBuilderLike valueBuilder) {
        return cast(type(toType), valueBuilder);
    }

    /**
     * Instantiate a new instance of a type.
     * @param type Class to instantiate.
     * @param parameters List of parameters taken by the target constructor.
     * @param paramBuilders Code builders which stack values to pass as parameters to the invoked constructor.
     * @return A code builder which produces the bytecode to construct a new instance of a type.
     * @see #instantiate(Class, CodeInsnBuilderLike...)
     * @see #instantiate(TypeDefinition, CodeInsnBuilderLike...)
     * @see #instantiate(Class, ParametersDefinition, CodeInsnBuilderLike...)
     */
    public static InstantiateObjectInsn instantiate(TypeDefinition type, ParametersDefinition parameters, CodeInsnBuilderLike... paramBuilders) {
        return new InstantiateObjectInsn(type, parameters, paramBuilders);
    }

    /**
     * Instantiate a new instance of a type.
     * @param type Class to instantiate.
     * @param parameters List of parameters taken by the target constructor.
     * @param paramBuilders Code builders which stack values to pass as parameters to the invoked constructor.
     * @return A code builder which produces the bytecode to construct a new instance of a type.
     * @see #instantiate(Class, CodeInsnBuilderLike...)
     * @see #instantiate(TypeDefinition, CodeInsnBuilderLike...)
     * @see #instantiate(TypeDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     */
    public static InstantiateObjectInsn instantiate(Class<?> type, ParametersDefinition parameters, CodeInsnBuilderLike... paramBuilders) {
        return instantiate(type(type), parameters, paramBuilders);
    }

    /**
     * Instantiate a new instance of a type. Parameters list will be implied from the values placed on the jvm stack
     * by the paramBuilders.
     * @param type Class to instantiate.
     * @param paramBuilders Code builders which stack values to pass as parameters to the invoked constructor.
     * @return A code builder which produces the bytecode to construct a new instance of a type.
     * @see #instantiate(Class, CodeInsnBuilderLike...)
     * @see #instantiate(Class, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #instantiate(TypeDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     */
    public static InstantiateObjectInsn instantiate(TypeDefinition type, CodeInsnBuilderLike... paramBuilders) {
        return new InstantiateObjectInsn(type, paramBuilders);
    }

    /**
     * Instantiate a new instance of a type. Parameters list will be implied from the values placed on the jvm stack
     * by the paramBuilders.
     * @param type Class to instantiate.
     * @param paramBuilders Code builders which stack values to pass as parameters to the invoked constructor.
     * @return A code builder which produces the bytecode to construct a new instance of a type.
     * @see #instantiate(TypeDefinition, CodeInsnBuilderLike...)
     * @see #instantiate(Class, ParametersDefinition, CodeInsnBuilderLike...)
     * @see #instantiate(TypeDefinition, ParametersDefinition, CodeInsnBuilderLike...)
     */
    public static InstantiateObjectInsn instantiate(Class<?> type, CodeInsnBuilderLike... paramBuilders) {
        return instantiate(type(type), paramBuilders);
    }

    /**
     * Creates a block of code containing the 0 or more given code builders.
     * @param builders The code builders to put into a block.
     * @return A code block wrapping zero or more code builders. This code block will execute all of the code builders
     *         so all of their bytecode gets generated.
     */
    public static CodeBlock block(CodeInsnBuilderLike... builders) {
        return new CodeBlock(builders);
    }

    /**
     * Begins the building of an if-statement.
     * @param condition A truth condition.
     * @return An IfBranch builder which will allow the if-statement to be completed with a body and else block if desired.
     */
    public static IfBranch.IfBuilder if_(Condition condition) {
        return new IfBranch.IfBuilder(condition);
    }

    /**
     * Begins the building of a while-loop.
     * @param condition A truth condition.
     * @return A WhileLoop builder which will allow the while-loop to be completed with a body.
     * The built while loop will execute that code body until the provided truth condition becomes false.
     */
    public static WhileLoop.WhileBuilder while_(Condition condition) {
        return new WhileLoop.WhileBuilder(condition);
    }

    /**
     * Inverts a condition. This is the equivalent of !condition.
     * @param condition The condition to invert.
     * @return The inverted condition.
     */
    public static Condition not(Condition condition) {
        return condition.invert();
    }
}