package io.github.cshunsinger.asmsauce.code.field;

import io.github.cshunsinger.asmsauce.code.array.AccessibleArrayLike;
import io.github.cshunsinger.asmsauce.code.branch.condition.BooleanConditionBuilderLike;
import io.github.cshunsinger.asmsauce.code.branch.condition.ConditionBuilderLike;
import io.github.cshunsinger.asmsauce.code.branch.condition.NullConditionBuilderLike;
import io.github.cshunsinger.asmsauce.code.math.MathOperandInstance;
import io.github.cshunsinger.asmsauce.code.method.InvokableInstance;
import io.github.cshunsinger.asmsauce.definitions.FieldDefinition;
import io.github.cshunsinger.asmsauce.definitions.TypeDefinition;

import java.util.Stack;

import static org.objectweb.asm.Opcodes.GETSTATIC;

/**
 * This is a code builder for generating bytecode to fetch a value from a static field.
 */
public class GetStaticFieldInsn extends FieldInsn implements
    InvokableInstance, FieldAccessibleInstance, MathOperandInstance, ConditionBuilderLike,
    BooleanConditionBuilderLike, NullConditionBuilderLike, AccessibleArrayLike {

    /**
     * Instantiates this code builder from a defined field.
     * @param fieldDefinition The static field to fetch a value from in the generated bytecode.
     * @throws IllegalArgumentException If fieldDefinition is null.
     * @throws IllegalArgumentException If fieldDefinition defines an instance field.
     */
    public GetStaticFieldInsn(FieldDefinition fieldDefinition) {
        super(fieldDefinition);

        if(!fieldDefinition.getAccessModifiers().isStatic()) {
            throw new IllegalArgumentException(
                "This instruction only handles getting static fields. Field '%s.%s' is not static.".formatted(
                    fieldDefinition.getFieldType().getType().getName(),
                    fieldDefinition.getFieldName().getName()
                )
            );
        }
    }

    @Override
    public void build() {
        Class<?> fieldOwnerClass = fieldDefinition.getFieldOwner().getType();

        if(fieldOwnerClass.isArray())
            throw new IllegalStateException("Cannot access static field from array type %s.".formatted(fieldOwnerClass.getSimpleName()));

        fieldDefinition = fieldDefinition.completeDefinition();

        super.build();
    }

    @Override
    protected void performTypeStackChanges(Stack<TypeDefinition> typeStack) {
        //Push the field value type onto the stack
        typeStack.push(fieldDefinition.getFieldType());
    }

    @Override
    protected int instruction() {
        return GETSTATIC;
    }

    @Override
    protected TypeDefinition determineFieldOwner(Stack<TypeDefinition> typeStack) {
        return fieldDefinition.getFieldOwner();
    }
}